name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 103.52.114.134 >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name : update pip
        run : pip install --upgrade pip

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@103.52.114.134 "mkdir -p /home/kray/project-python"
          scp -r UTS/ root@103.52.114.134:/home/kray/project-python/
